import { ChackrauiProvider } from "@/providers/ChakrauiProvider";
import "animate.css";
import "./globals.css";
import { Inter } from "next/font/google";
import { ReactQueryProvider } from "@/providers/ReactQueryProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Layouts/Footer";
import RecoilProvider from "@/providers/state-providers/RecoilStateProviders/RecoilProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilProvider>
          <ReactQueryProvider>
            <ChackrauiProvider>
              <Navbar />
              {children}
              <Footer />
            </ChackrauiProvider>
          </ReactQueryProvider>
        </RecoilProvider>
      </body>
    </html>
  );
}
